# Generated by Django 6.0.2 on 2026-03-10 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaParkir',
            fields=[
                ('kd_area', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_area', models.CharField(max_length=50)),
                ('kapasitas', models.IntegerField()),
            ],
            options={
                'db_table': 'area_parkir',
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namaLengkap', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='TransaksiParkir',
            fields=[
                ('kd_transaksi', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('waktu_masuk', models.DateTimeField()),
                ('waktu_keluar', models.DateTimeField(blank=True, default=None, null=True)),
                ('biaya', models.IntegerField(blank=True, default=0, null=True)),
                ('jenis_kendaraan', models.CharField(default='Motor', max_length=20)),
                ('status', models.CharField(choices=[('IN', 'Masuk'), ('OUT', 'Keluar'), ('DONE', 'Selesai'), ('PENDING_IN', 'Menunggu Masuk'), ('PENDING_OUT', 'Menunggu Keluar')], default='PENDING_IN', max_length=20)),
                ('id_transaksi', models.CharField(max_length=50)),
                ('noPlat', models.CharField(max_length=20)),
                ('card_id', models.CharField(default='', max_length=50)),
                ('kd_area', models.ForeignKey(db_column='kd_area', on_delete=django.db.models.deletion.CASCADE, to='parkir.areaparkir')),
            ],
            options={
                'db_table': 'transaksi_parkir',
            },
        ),
    ]
