# Generated by Django 6.0.3 on 2026-03-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrukQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_transaksi', models.CharField(max_length=10)),
                ('struk', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sudah_diambil', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'struk_queue',
            },
        ),
        migrations.AlterField(
            model_name='transaksiparkir',
            name='kd_transaksi',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksiparkir',
            name='status',
            field=models.CharField(choices=[('IN', 'Masuk'), ('OUT', 'Keluar'), ('DONE', 'Selesai')], default='IN', max_length=20),
        ),
    ]
